Pig Stack Trace
---------------
ERROR 6000: Output Location Validation Failed for: 'hdfs://smithers.cs.indiana.edu:9000/user/midconov/analysis/timestamps/romney_ts More info to follow:
Output directory hdfs://smithers.cs.indiana.edu:9000/user/midconov/analysis/timestamps/romney_ts already exists

org.apache.pig.impl.logicalLayer.FrontendException: ERROR 1002: Unable to store alias 20
	at org.apache.pig.PigServer$Graph.registerQuery(PigServer.java:1580)
	at org.apache.pig.PigServer.registerQuery(PigServer.java:534)
	at org.apache.pig.tools.grunt.GruntParser.processPig(GruntParser.java:871)
	at org.apache.pig.tools.pigscript.parser.PigScriptParser.parse(PigScriptParser.java:388)
	at org.apache.pig.tools.grunt.GruntParser.parseStopOnError(GruntParser.java:168)
	at org.apache.pig.tools.grunt.GruntParser.parseStopOnError(GruntParser.java:144)
	at org.apache.pig.tools.grunt.Grunt.run(Grunt.java:76)
	at org.apache.pig.Main.run(Main.java:455)
	at org.apache.pig.Main.main(Main.java:107)
Caused by: org.apache.pig.impl.logicalLayer.FrontendException: ERROR 2042: Error in new logical plan. Try -Dpig.usenewlogicalplan=false.
	at org.apache.pig.backend.hadoop.executionengine.HExecutionEngine.compile(HExecutionEngine.java:313)
	at org.apache.pig.PigServer.compilePp(PigServer.java:1365)
	at org.apache.pig.PigServer.executeCompiledLogicalPlan(PigServer.java:1207)
	at org.apache.pig.PigServer.execute(PigServer.java:1201)
	at org.apache.pig.PigServer.access$100(PigServer.java:129)
	at org.apache.pig.PigServer$Graph.execute(PigServer.java:1528)
	at org.apache.pig.PigServer$Graph.registerQuery(PigServer.java:1575)
	... 8 more
Caused by: org.apache.pig.impl.logicalLayer.FrontendException: ERROR 6000: Output Location Validation Failed for: 'hdfs://smithers.cs.indiana.edu:9000/user/midconov/analysis/timestamps/romney_ts More info to follow:
Output directory hdfs://smithers.cs.indiana.edu:9000/user/midconov/analysis/timestamps/romney_ts already exists
	at org.apache.pig.newplan.logical.rules.InputOutputFileValidator$InputOutputFileVisitor.visit(InputOutputFileValidator.java:102)
	at org.apache.pig.newplan.logical.relational.LOStore.accept(LOStore.java:76)
	at org.apache.pig.newplan.DepthFirstWalker.depthFirst(DepthFirstWalker.java:64)
	at org.apache.pig.newplan.DepthFirstWalker.depthFirst(DepthFirstWalker.java:66)
	at org.apache.pig.newplan.DepthFirstWalker.depthFirst(DepthFirstWalker.java:66)
	at org.apache.pig.newplan.DepthFirstWalker.depthFirst(DepthFirstWalker.java:66)
	at org.apache.pig.newplan.DepthFirstWalker.depthFirst(DepthFirstWalker.java:66)
	at org.apache.pig.newplan.DepthFirstWalker.walk(DepthFirstWalker.java:53)
	at org.apache.pig.newplan.PlanVisitor.visit(PlanVisitor.java:50)
	at org.apache.pig.newplan.logical.rules.InputOutputFileValidator.validate(InputOutputFileValidator.java:52)
	at org.apache.pig.backend.hadoop.executionengine.HExecutionEngine.compile(HExecutionEngine.java:292)
	... 14 more
Caused by: org.apache.hadoop.mapred.FileAlreadyExistsException: Output directory hdfs://smithers.cs.indiana.edu:9000/user/midconov/analysis/timestamps/romney_ts already exists
	at org.apache.hadoop.mapreduce.lib.output.FileOutputFormat.checkOutputSpecs(FileOutputFormat.java:132)
	at org.apache.pig.newplan.logical.rules.InputOutputFileValidator$InputOutputFileVisitor.visit(InputOutputFileValidator.java:87)
	... 24 more
================================================================================
Pig Stack Trace
---------------
ERROR 6000: Output Location Validation Failed for: 'hdfs://smithers.cs.indiana.edu:9000/user/midconov/analysis/timestamps/romney_ts More info to follow:
Output directory hdfs://smithers.cs.indiana.edu:9000/user/midconov/analysis/timestamps/romney_ts already exists

org.apache.pig.impl.logicalLayer.FrontendException: ERROR 1002: Unable to store alias 36
	at org.apache.pig.PigServer$Graph.registerQuery(PigServer.java:1580)
	at org.apache.pig.PigServer.registerQuery(PigServer.java:534)
	at org.apache.pig.tools.grunt.GruntParser.processPig(GruntParser.java:871)
	at org.apache.pig.tools.pigscript.parser.PigScriptParser.parse(PigScriptParser.java:388)
	at org.apache.pig.tools.grunt.GruntParser.parseStopOnError(GruntParser.java:168)
	at org.apache.pig.tools.grunt.GruntParser.parseStopOnError(GruntParser.java:144)
	at org.apache.pig.tools.grunt.Grunt.run(Grunt.java:76)
	at org.apache.pig.Main.run(Main.java:455)
	at org.apache.pig.Main.main(Main.java:107)
Caused by: org.apache.pig.impl.logicalLayer.FrontendException: ERROR 2042: Error in new logical plan. Try -Dpig.usenewlogicalplan=false.
	at org.apache.pig.backend.hadoop.executionengine.HExecutionEngine.compile(HExecutionEngine.java:313)
	at org.apache.pig.PigServer.compilePp(PigServer.java:1365)
	at org.apache.pig.PigServer.executeCompiledLogicalPlan(PigServer.java:1207)
	at org.apache.pig.PigServer.execute(PigServer.java:1201)
	at org.apache.pig.PigServer.access$100(PigServer.java:129)
	at org.apache.pig.PigServer$Graph.execute(PigServer.java:1528)
	at org.apache.pig.PigServer$Graph.registerQuery(PigServer.java:1575)
	... 8 more
Caused by: org.apache.pig.impl.logicalLayer.FrontendException: ERROR 6000: Output Location Validation Failed for: 'hdfs://smithers.cs.indiana.edu:9000/user/midconov/analysis/timestamps/romney_ts More info to follow:
Output directory hdfs://smithers.cs.indiana.edu:9000/user/midconov/analysis/timestamps/romney_ts already exists
	at org.apache.pig.newplan.logical.rules.InputOutputFileValidator$InputOutputFileVisitor.visit(InputOutputFileValidator.java:102)
	at org.apache.pig.newplan.logical.relational.LOStore.accept(LOStore.java:76)
	at org.apache.pig.newplan.DepthFirstWalker.depthFirst(DepthFirstWalker.java:64)
	at org.apache.pig.newplan.DepthFirstWalker.depthFirst(DepthFirstWalker.java:66)
	at org.apache.pig.newplan.DepthFirstWalker.depthFirst(DepthFirstWalker.java:66)
	at org.apache.pig.newplan.DepthFirstWalker.depthFirst(DepthFirstWalker.java:66)
	at org.apache.pig.newplan.DepthFirstWalker.depthFirst(DepthFirstWalker.java:66)
	at org.apache.pig.newplan.DepthFirstWalker.walk(DepthFirstWalker.java:53)
	at org.apache.pig.newplan.PlanVisitor.visit(PlanVisitor.java:50)
	at org.apache.pig.newplan.logical.rules.InputOutputFileValidator.validate(InputOutputFileValidator.java:52)
	at org.apache.pig.backend.hadoop.executionengine.HExecutionEngine.compile(HExecutionEngine.java:292)
	... 14 more
Caused by: org.apache.hadoop.mapred.FileAlreadyExistsException: Output directory hdfs://smithers.cs.indiana.edu:9000/user/midconov/analysis/timestamps/romney_ts already exists
	at org.apache.hadoop.mapreduce.lib.output.FileOutputFormat.checkOutputSpecs(FileOutputFormat.java:132)
	at org.apache.pig.newplan.logical.rules.InputOutputFileValidator$InputOutputFileVisitor.visit(InputOutputFileValidator.java:87)
	... 24 more
================================================================================
Pig Stack Trace
---------------
ERROR 6000: Output Location Validation Failed for: 'hdfs://smithers.cs.indiana.edu:9000/user/midconov/analysis/timestamps/romney_ts More info to follow:
Output directory hdfs://smithers.cs.indiana.edu:9000/user/midconov/analysis/timestamps/romney_ts already exists

org.apache.pig.impl.logicalLayer.FrontendException: ERROR 1002: Unable to store alias 53
	at org.apache.pig.PigServer$Graph.registerQuery(PigServer.java:1580)
	at org.apache.pig.PigServer.registerQuery(PigServer.java:534)
	at org.apache.pig.tools.grunt.GruntParser.processPig(GruntParser.java:871)
	at org.apache.pig.tools.pigscript.parser.PigScriptParser.parse(PigScriptParser.java:388)
	at org.apache.pig.tools.grunt.GruntParser.parseStopOnError(GruntParser.java:168)
	at org.apache.pig.tools.grunt.GruntParser.parseStopOnError(GruntParser.java:144)
	at org.apache.pig.tools.grunt.Grunt.run(Grunt.java:76)
	at org.apache.pig.Main.run(Main.java:455)
	at org.apache.pig.Main.main(Main.java:107)
Caused by: org.apache.pig.impl.logicalLayer.FrontendException: ERROR 2042: Error in new logical plan. Try -Dpig.usenewlogicalplan=false.
	at org.apache.pig.backend.hadoop.executionengine.HExecutionEngine.compile(HExecutionEngine.java:313)
	at org.apache.pig.PigServer.compilePp(PigServer.java:1365)
	at org.apache.pig.PigServer.executeCompiledLogicalPlan(PigServer.java:1207)
	at org.apache.pig.PigServer.execute(PigServer.java:1201)
	at org.apache.pig.PigServer.access$100(PigServer.java:129)
	at org.apache.pig.PigServer$Graph.execute(PigServer.java:1528)
	at org.apache.pig.PigServer$Graph.registerQuery(PigServer.java:1575)
	... 8 more
Caused by: org.apache.pig.impl.logicalLayer.FrontendException: ERROR 6000: Output Location Validation Failed for: 'hdfs://smithers.cs.indiana.edu:9000/user/midconov/analysis/timestamps/romney_ts More info to follow:
Output directory hdfs://smithers.cs.indiana.edu:9000/user/midconov/analysis/timestamps/romney_ts already exists
	at org.apache.pig.newplan.logical.rules.InputOutputFileValidator$InputOutputFileVisitor.visit(InputOutputFileValidator.java:102)
	at org.apache.pig.newplan.logical.relational.LOStore.accept(LOStore.java:76)
	at org.apache.pig.newplan.DepthFirstWalker.depthFirst(DepthFirstWalker.java:64)
	at org.apache.pig.newplan.DepthFirstWalker.depthFirst(DepthFirstWalker.java:66)
	at org.apache.pig.newplan.DepthFirstWalker.depthFirst(DepthFirstWalker.java:66)
	at org.apache.pig.newplan.DepthFirstWalker.depthFirst(DepthFirstWalker.java:66)
	at org.apache.pig.newplan.DepthFirstWalker.depthFirst(DepthFirstWalker.java:66)
	at org.apache.pig.newplan.DepthFirstWalker.walk(DepthFirstWalker.java:53)
	at org.apache.pig.newplan.PlanVisitor.visit(PlanVisitor.java:50)
	at org.apache.pig.newplan.logical.rules.InputOutputFileValidator.validate(InputOutputFileValidator.java:52)
	at org.apache.pig.backend.hadoop.executionengine.HExecutionEngine.compile(HExecutionEngine.java:292)
	... 14 more
Caused by: org.apache.hadoop.mapred.FileAlreadyExistsException: Output directory hdfs://smithers.cs.indiana.edu:9000/user/midconov/analysis/timestamps/romney_ts already exists
	at org.apache.hadoop.mapreduce.lib.output.FileOutputFormat.checkOutputSpecs(FileOutputFormat.java:132)
	at org.apache.pig.newplan.logical.rules.InputOutputFileValidator$InputOutputFileVisitor.visit(InputOutputFileValidator.java:87)
	... 24 more
================================================================================
Pig Stack Trace
---------------
ERROR 2043: Unexpected error during execution.

org.apache.pig.impl.logicalLayer.FrontendException: ERROR 1002: Unable to store alias 254
	at org.apache.pig.PigServer$Graph.registerQuery(PigServer.java:1580)
	at org.apache.pig.PigServer.registerQuery(PigServer.java:534)
	at org.apache.pig.tools.grunt.GruntParser.processPig(GruntParser.java:871)
	at org.apache.pig.tools.pigscript.parser.PigScriptParser.parse(PigScriptParser.java:388)
	at org.apache.pig.tools.grunt.GruntParser.parseStopOnError(GruntParser.java:168)
	at org.apache.pig.tools.grunt.GruntParser.parseStopOnError(GruntParser.java:144)
	at org.apache.pig.tools.grunt.Grunt.run(Grunt.java:76)
	at org.apache.pig.Main.run(Main.java:455)
	at org.apache.pig.Main.main(Main.java:107)
Caused by: org.apache.pig.backend.executionengine.ExecException: ERROR 2043: Unexpected error during execution.
	at org.apache.pig.backend.hadoop.executionengine.HExecutionEngine.execute(HExecutionEngine.java:407)
	at org.apache.pig.PigServer.executeCompiledLogicalPlan(PigServer.java:1209)
	at org.apache.pig.PigServer.execute(PigServer.java:1201)
	at org.apache.pig.PigServer.access$100(PigServer.java:129)
	at org.apache.pig.PigServer$Graph.execute(PigServer.java:1528)
	at org.apache.pig.PigServer$Graph.registerQuery(PigServer.java:1575)
	... 8 more
Caused by: java.io.IOException: Call to smithers.cs.indiana.edu/129.79.247.20:9001 failed on local exception: java.io.IOException: Connection reset by peer
	at org.apache.hadoop.ipc.Client.wrapException(Client.java:1142)
	at org.apache.hadoop.ipc.Client.call(Client.java:1110)
	at org.apache.hadoop.ipc.RPC$Invoker.invoke(RPC.java:226)
	at org.apache.hadoop.mapred.$Proxy1.getJobStatus(Unknown Source)
	at org.apache.hadoop.mapred.JobClient.getJob(JobClient.java:1053)
	at org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.Launcher.progressOfRunningJob(Launcher.java:278)
	at org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.Launcher.calculateProgress(Launcher.java:261)
	at org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.MapReduceLauncher.launchPig(MapReduceLauncher.java:253)
	at org.apache.pig.backend.hadoop.executionengine.HExecutionEngine.execute(HExecutionEngine.java:382)
	... 13 more
Caused by: java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:21)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:198)
	at sun.nio.ch.IOUtil.read(IOUtil.java:171)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:243)
	at org.apache.hadoop.net.SocketInputStream$Reader.performIO(SocketInputStream.java:55)
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:142)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.FilterInputStream.read(FilterInputStream.java:116)
	at org.apache.hadoop.ipc.Client$Connection$PingInputStream.read(Client.java:375)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:218)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:237)
	at java.io.DataInputStream.readInt(DataInputStream.java:370)
	at org.apache.hadoop.ipc.Client$Connection.receiveResponse(Client.java:815)
	at org.apache.hadoop.ipc.Client$Connection.run(Client.java:724)
================================================================================
Pig Stack Trace
---------------
ERROR 2043: Unexpected error during execution.

org.apache.pig.impl.logicalLayer.FrontendException: ERROR 1002: Unable to store alias 317
	at org.apache.pig.PigServer$Graph.registerQuery(PigServer.java:1580)
	at org.apache.pig.PigServer.registerQuery(PigServer.java:534)
	at org.apache.pig.tools.grunt.GruntParser.processPig(GruntParser.java:871)
	at org.apache.pig.tools.pigscript.parser.PigScriptParser.parse(PigScriptParser.java:388)
	at org.apache.pig.tools.grunt.GruntParser.parseStopOnError(GruntParser.java:168)
	at org.apache.pig.tools.grunt.GruntParser.parseStopOnError(GruntParser.java:144)
	at org.apache.pig.tools.grunt.Grunt.run(Grunt.java:76)
	at org.apache.pig.Main.run(Main.java:455)
	at org.apache.pig.Main.main(Main.java:107)
Caused by: org.apache.pig.backend.executionengine.ExecException: ERROR 2043: Unexpected error during execution.
	at org.apache.pig.backend.hadoop.executionengine.HExecutionEngine.execute(HExecutionEngine.java:407)
	at org.apache.pig.PigServer.executeCompiledLogicalPlan(PigServer.java:1209)
	at org.apache.pig.PigServer.execute(PigServer.java:1201)
	at org.apache.pig.PigServer.access$100(PigServer.java:129)
	at org.apache.pig.PigServer$Graph.execute(PigServer.java:1528)
	at org.apache.pig.PigServer$Graph.registerQuery(PigServer.java:1575)
	... 8 more
Caused by: java.net.ConnectException: Call to smithers.cs.indiana.edu/129.79.247.20:9001 failed on connection exception: java.net.ConnectException: Connection refused
	at org.apache.hadoop.ipc.Client.wrapException(Client.java:1134)
	at org.apache.hadoop.ipc.Client.call(Client.java:1110)
	at org.apache.hadoop.ipc.RPC$Invoker.invoke(RPC.java:226)
	at org.apache.hadoop.mapred.$Proxy1.getProtocolVersion(Unknown Source)
	at org.apache.hadoop.ipc.RPC.getProxy(RPC.java:398)
	at org.apache.hadoop.ipc.RPC.getProxy(RPC.java:384)
	at org.apache.hadoop.mapred.JobClient.createRPCProxy(JobClient.java:501)
	at org.apache.hadoop.mapred.JobClient.init(JobClient.java:486)
	at org.apache.hadoop.mapred.JobClient.<init>(JobClient.java:469)
	at org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.MapReduceLauncher.launchPig(MapReduceLauncher.java:122)
	at org.apache.pig.backend.hadoop.executionengine.HExecutionEngine.execute(HExecutionEngine.java:382)
	... 13 more
Caused by: java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:567)
	at org.apache.hadoop.net.SocketIOWithTimeout.connect(SocketIOWithTimeout.java:206)
	at org.apache.hadoop.net.NetUtils.connect(NetUtils.java:408)
	at org.apache.hadoop.ipc.Client$Connection.setupConnection(Client.java:425)
	at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:532)
	at org.apache.hadoop.ipc.Client$Connection.access$2300(Client.java:210)
	at org.apache.hadoop.ipc.Client.getConnection(Client.java:1247)
	at org.apache.hadoop.ipc.Client.call(Client.java:1078)
	... 22 more
================================================================================
Pig Stack Trace
---------------
ERROR 2043: Unexpected error during execution.

org.apache.pig.impl.logicalLayer.FrontendException: ERROR 1002: Unable to store alias 381
	at org.apache.pig.PigServer$Graph.registerQuery(PigServer.java:1580)
	at org.apache.pig.PigServer.registerQuery(PigServer.java:534)
	at org.apache.pig.tools.grunt.GruntParser.processPig(GruntParser.java:871)
	at org.apache.pig.tools.pigscript.parser.PigScriptParser.parse(PigScriptParser.java:388)
	at org.apache.pig.tools.grunt.GruntParser.parseStopOnError(GruntParser.java:168)
	at org.apache.pig.tools.grunt.GruntParser.parseStopOnError(GruntParser.java:144)
	at org.apache.pig.tools.grunt.Grunt.run(Grunt.java:76)
	at org.apache.pig.Main.run(Main.java:455)
	at org.apache.pig.Main.main(Main.java:107)
Caused by: org.apache.pig.backend.executionengine.ExecException: ERROR 2043: Unexpected error during execution.
	at org.apache.pig.backend.hadoop.executionengine.HExecutionEngine.execute(HExecutionEngine.java:407)
	at org.apache.pig.PigServer.executeCompiledLogicalPlan(PigServer.java:1209)
	at org.apache.pig.PigServer.execute(PigServer.java:1201)
	at org.apache.pig.PigServer.access$100(PigServer.java:129)
	at org.apache.pig.PigServer$Graph.execute(PigServer.java:1528)
	at org.apache.pig.PigServer$Graph.registerQuery(PigServer.java:1575)
	... 8 more
Caused by: java.net.ConnectException: Call to smithers.cs.indiana.edu/129.79.247.20:9001 failed on connection exception: java.net.ConnectException: Connection refused
	at org.apache.hadoop.ipc.Client.wrapException(Client.java:1134)
	at org.apache.hadoop.ipc.Client.call(Client.java:1110)
	at org.apache.hadoop.ipc.RPC$Invoker.invoke(RPC.java:226)
	at org.apache.hadoop.mapred.$Proxy1.getProtocolVersion(Unknown Source)
	at org.apache.hadoop.ipc.RPC.getProxy(RPC.java:398)
	at org.apache.hadoop.ipc.RPC.getProxy(RPC.java:384)
	at org.apache.hadoop.mapred.JobClient.createRPCProxy(JobClient.java:501)
	at org.apache.hadoop.mapred.JobClient.init(JobClient.java:486)
	at org.apache.hadoop.mapred.JobClient.<init>(JobClient.java:469)
	at org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.MapReduceLauncher.launchPig(MapReduceLauncher.java:122)
	at org.apache.pig.backend.hadoop.executionengine.HExecutionEngine.execute(HExecutionEngine.java:382)
	... 13 more
Caused by: java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:567)
	at org.apache.hadoop.net.SocketIOWithTimeout.connect(SocketIOWithTimeout.java:206)
	at org.apache.hadoop.net.NetUtils.connect(NetUtils.java:408)
	at org.apache.hadoop.ipc.Client$Connection.setupConnection(Client.java:425)
	at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:532)
	at org.apache.hadoop.ipc.Client$Connection.access$2300(Client.java:210)
	at org.apache.hadoop.ipc.Client.getConnection(Client.java:1247)
	at org.apache.hadoop.ipc.Client.call(Client.java:1078)
	... 22 more
================================================================================
